### ISSUE TITLE
Doesn't work with CSS Nesting

### ISSUE THREAD

**Issue by reify-benjamin-solum** [Moxio/stylelint-selector-tag-no-without-class#20]
`button.tag` and `.tag svg` are currently treated as violations with CSS Nesting:

```css
.tag {
  &button {
    cursor: pointer;
  }

  & svg {
    color: currentcolor;
    width: 0.8em;
  }
}
```
