### ISSUE TITLE
Support nested selectors

### ISSUE THREAD

**Issue by ekilah** [Moxio/stylelint-selector-tag-no-without-class#4]
```css
.someClass {
  padding: 20px;

  & h2 {
    width: 500px;
  }
}
```

This CSS should not be considered invalid by this plugin, but is. Many of the default rules in `stylelint` understand the meaning of this nesting operator `&`, I'm not sure how much work it would be to support from your plugin.
